server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/gimnasio_db?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=24Daniel42

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.jpa.defer-datasource-initialization=true

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.error.include-message=always
server.error.include-binding-errors=always

logging.level.com.purpleforce=INFO
logging.level.org.springframework.security=WARN
logging.file.name=logs/purpleforce.log